Repository Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded, pull requests merged in 2022-12, with the labels that each got.

#71 Locales - update localization parameter
  APR-Core/APR-Core.toc
  APR-Core/Locales.xml
  APR-Core/locales/deDE.lua
  APR-Core/locales/enUS.lua
  APR-Core/locales/esES.lua
  APR-Core/locales/esMX.lua
  APR-Core/locales/frFR.lua
  APR-Core/locales/itIT.lua
  APR-Core/locales/koKR.lua
  APR-Core/locales/ptBR.lua
  APR-Core/locales/ruRU.lua
  APR-Core/locales/zhCN.lua
  APR-Core/locales/zhTW.lua
Labels: Translation

#75 Fix button quest ID and zone 4 for the horde
  APR-Core/QuestHandler.lua
  APR-Core/QuestTest.lua
  APR-Dragonflight/Dragonflight.lua
  APR-Dragonflight/Dragonflight_Alliance.lua
  APR-Dragonflight/Dragonflight_horde.lua
Labels: Bug, Feature, Priority

#76 Death guide update & route prettier
  APR-BattleForAzeroth/BattleForAzeroth.lua
  APR-BattleForAzeroth/BattleForAzeroth_Alliance.lua
  APR-BattleForAzeroth/BattleForAzeroth_Horde.lua
  APR-Core/Core.lua
  APR-Core/QuestHandler.lua
  APR-Core/TransportDB.lua
  APR-Core/zones/Alliance.lua
  APR-Core/zones/Horde.lua
  APR-Core/zones/Neutral.lua
  APR-ExilesReach/ExilesReach_Alliance.lua
  APR-ExilesReach/ExilesReach_Horde.lua
  APR-Legion/Legion.lua
  APR-MistsOfPandaria/MistsOfPandaria_Horde.lua
  APR-Shadowlands/Shadowlands.lua
  APR-Vanilla/EasternKingdoms_Alliance.lua
  APR-Vanilla/EasternKingdoms_Horde.lua
  APR-Vanilla/Kalimdor_Alliance.lua
  APR-Vanilla/Kalimdor_Horde.lua
  APR-WarlordsOfDraenor/WarlordsOfDraenor_Alliance.lua
  APR-WarlordsOfDraenor/WarlordsOfDraenor_Horde.lua
Labels: Bug, Translation

#80 Add First character path and fix some error/warning
  APR-BattleForAzeroth/BattleForAzeroth_Alliance.lua
  APR-BattleForAzeroth/BattleForAzeroth_Horde.lua
  APR-Core/Core.lua
  APR-Core/QuestHandler.lua
  APR-Core/Transport.lua
  APR-Core/lib/Utils.lua
  APR-Core/zones/Alliance.lua
  APR-Core/zones/Horde.lua
  APR-Dragonflight/Dragonflight.lua
  APR-WarlordsOfDraenor/WarlordsOfDraenor_Alliance.lua
  APR-WarlordsOfDraenor/WarlordsOfDraenor_Horde.lua
Labels: Bug, Feature

#81 Fix auto pick quest reward and deprecated player choice update event
  APR-Core/QuestHandler.lua
Labels: Bug

#83 Fix chromie and outpost selection
  APR-Core/QuestHandler.lua
  APR-Core/lib/Utils.lua
Labels: Bug, Priority

#96 Remove "blank" step in BFA Horde route
  APR-BattleForAzeroth/BattleForAzeroth_Horde.lua
Labels: Bug

#94 Add new feature and question templates + Bug report form template
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/issue-report.md
Labels: Documentation

#97 Change the WOD steps order with a vanilla alliance character
  APR-Core/QuestHandler.lua
  APR-WarlordsOfDraenor/WarlordsOfDraenor_Alliance.lua
Labels: Bug

#98 Add route question to Bug/issue templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/issue-report.md
Labels: Documentation

#99 Hearthstoning out from zone causes pathing to bug out for Argus and Maelstrom
  APR-Core/QuestHandler.lua
Labels: Bug

#100 Manage Timeline extra line text for WOD
  APR-Core/QuestHandler.lua
  APR-Core/Transport.lua
Labels: Bug

#101 Update issue templates (remove issue report for bug report)
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/issue-report.md
Labels: Documentation
